### ISSUE TITLE
Travis setup is not ideal for pull requests

### ISSUE THREAD

**Issue by pawelgalazka** [pawelgalazka/runjs#17]
Current travis setup:
```yml
language: node_js
node_js:
  - "4.1"
before_script:
  - npm install -g pawelgalazka/runjs
script: run test
```

It install runjs script from master branch so it will not test the script from pull request.
